

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mochanetwork

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29093,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29093,PLAINTEXT_HOST://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - mochanetwork

  authService:
    build: ./services/auth-service
    container_name: Mocha-auth-service_c
    image: abshar777/mocha-auth-service
    restart: unless-stopped
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - kafka
    ports:
      - 4000:4000
    networks: 
      - mochanetwork
    develop:
      watch:
        - action: sync
          path: ./services/auth-service
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/auth-service/package.json

  userService:
    build: ./services/user-service
    container_name: Mocha-user-service_c
    image: abshar777/mocha-user-service
    restart: unless-stopped
    env_file:
      - ./services/user-service/.env
    depends_on:
      - kafka
    ports:
      - 4001:4001
    networks: 
      - mochanetwork
    develop:
      watch:
        - action: sync
          path: ./services/user-service
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/user-service/package.json

  companyService:
    build: ./services/company-service
    container_name: Mocha-company-service_c
    image: abshar777/mocha-company-service
    restart: unless-stopped
    env_file:
      - ./services/company-service/.env
    depends_on:
      - kafka
    ports:
      - 4002:4002
    networks: 
      - mochanetwork
    develop:
      watch:
        - action: sync
          path: ./services/company-service
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/company-service/package.json



  nginx:
    build: ./gateway
    container_name: Mocha-nginx-gateway
    image: abshar777/mocha-nginx-gateway
    ports:
      - 8000:80
    networks:
      - mochanetwork
    depends_on:
      - authService
      - userService

networks:
  mochanetwork:
    driver: bridge
