name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or any branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/auth-service
          file: ./services/auth-service/Dockerfile
          push: true
          tags: abshar777/mocha-auth-service:latest

      - name: Build and push user-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/user-service
          file: ./services/user-service/Dockerfile
          push: true
          tags: abshar777/mocha-user-service:latest

      - name: Build and push nginx-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: abshar777/mocha-nginx-gateway:latest
